version: '3.9'

services:
  nginx-react:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - '${CLIENT_PORT}:80'
    environment:
      CLIENT_PORT: ${CLIENT_PORT}
